version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_kopi_challenge_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: kopi_challenge
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:


